### PR TITLE
Updated to SDK-20170920

### PR DESCRIPTION
**Pull request by krisztianloki**
This is a revised version of #20; cosmetic changes are now ignored and UniConsoleHelper is no longer introduced.

A slightly updated SDK from Amptek; the only major update seems to be fixes for issues when loading configurations from a file;

- if the file was larger than 512 it was truncated

- it is now mandatory to have a [DP5 SCA Configuration] line before the actual configuration items (this is how their windows tool creates the configuration file)

### CODE REVIEW

**Comment by MarkRivers** [comment]
@krisztianloki you have 4 pull requests from January 2021.  I would like to merge them if possible, but some work is needed.
- One of the requests looks wrong to me and I have added a review comment
- Two of the requests now have conflicts and cannot be directly merged.

Would you be able to fix these issues and test?

**Comment by krisztianloki** [comment]
Do you prefer a `rebase` or should I merge the current `master` into the conflicting branches and fix the conflicts?

**Comment by MarkRivers** [comment]
I suggest merging master and fixing conflicts. Thanks.

**Comment by MarkRivers** [comment]
Sorry I hit close by mistake.

**Pull request merged**
